[package]
name = "metis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vhost = "0.7.0"
vhost-user-backend = "0.9.0"
vm-memory = "0.11.0"
vmm-sys-util = "0.11.1"
